services:
  extractor:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    volumes:
      - ./data:/app/data
  
  uploader:
    build:
      context: .
      dockerfile: Dockerfile.uploader
    env_file:
      - .env
    volumes:
      - ./data:/app/data