services:
  extractor:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    volumes:
      - ./data:/app/data
  
  uploader:
    build:
      context: .
      dockerfile: Dockerfile.uploader
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  pyspark: 
    build: 
      context: . 
      dockerfile: Dockerfile.pyspark 
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes: 
      - ./:/home/jovyan/work 
    env_file: 
      - .env

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    env_file:
      - .env
    volumes:
      - ./data:/app/data
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
